### ISSUE TITLE
inconsistent license

### ISSUE THREAD

**Issue by Smallmelo** [codeforabq/Open-Budget-ABQ#13]
the license on this repo is MIT.  any reason why this was chosen as opposed to GNU v2.0 (like the rest of our repos)?

**Comment by bradweikel** [comment]
I don't think there was any rationale, only inertia. We announced the decision that gplv2 would be our default license on Aug 5. Florian committed the change with the MIT license the following week, but he'd probably had it in his local fork for quite some time before that. It just never got updated.

**Comment by HermesDev** [comment]
We don't need MIT in particular. If GNU v2.0 is the regular choice, we should probably go for it.

**Comment by FlorianGoussin** [comment]
Let's go for GNU v2.0 if that's the requirement.

**Comment by bradweikel** [comment]
not a requirement... just a brigade default. :)
