### ISSUE TITLE
7/14/2015 - Play w/ D3

### ISSUE THREAD

**Issue by codeforabq** [codeforabq/Open-Budget-ABQ#2]
What we want to do tonight:

Read about d3:
d3js.org

Pull code from Ashville's open budget app.  They ised react, d3, Laravel
http://communitybudgets.org/sites/asheville/whatsnew#
https://github.com/DemocracyApps/GBE/blob/master/gbe/resources/assets/js/components/aux/D3BarChart.js

Virtual Community Assessment Documment:
https://code4abq.slack.com/files/smallmelo/F07L3M9RA/virtualassessmentopenbudgetabq

Use the sample_budget_2014.csv file

**Comment by code4abq** [comment]
What actually happened tonight:

We set up the OpenBudget Repo, milestones, and issues.

Also: beer, free food, great conversations.

**Comment by codeforabq** [comment]
What actually happened tonight:

We set up the OpenBudget Repo, milestones, and issues.  A few folks started playing with D3, too.

Also: beer, free food, great conversations.
