### ISSUE TITLE
7/28/2015 - Play w/ D3

### ISSUE THREAD

**Issue by codeforabq** [codeforabq/Open-Budget-ABQ#3]
Resources:

Read about d3:
d3js.org

Pull code from Ashville's open budget app.  They ised react, d3, Laravel
http://communitybudgets.org/sites/asheville/whatsnew#
https://github.com/DemocracyApps/GBE/blob/master/gbe/resources/assets/js/components/aux/D3BarChart.js

Virtual Community Assessment Documment:
https://code4abq.slack.com/files/smallmelo/F07L3M9RA/virtualassessmentopenbudgetabq

Use the sample_budget_2014.csv file

**Comment by webmaven** [comment]
Please add me to the Slack group. Email is `michael (at) fandomhome (dot) com`.

**Comment by bradweikel** [comment]
We're well beyond this now, so I'm closing this issue. @webmaven I just sent you an invite to Slack -- apologies if you've been waiting.

**Comment by webmaven** [comment]
Thanks @bradweikel!
